[package]
name = "airship-rust"
version = "0.1.0"
authors = ["Kelly McLaughlin <kelly@kelly-mclaughlin.com>"]

[dependencies]
futures = "0.1.18"
hyper = "0.11"
mime = "0.3"
itertools = "0.7.8"
radix_trie = "0.1.3"