[package]
name = "webmachine_derive"
version = "0.1.0"
authors = ["Kelly McLaughlin <kelly.mclaughlin@joyent.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.5"
quote = "1.0.2"

[dependencies.proc-macro2]
version = "1.0"
default-features = false
